kind: pipeline
name: default

steps:
- name: server
  image: ruby:2.4-alpine3.9
  detach: true
  commands:
  - bundle install
  - ruby sinatra.rb

- name: client
  image: ruby:2.4-alpine3.9
  commands:
  - apk add curl
  - sleep 5
  - curl -v server:4567/ping
